# Generated by Django 4.2.6 on 2026-05-14 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('industry', models.CharField(choices=[('fashion', 'Fashion & Apparel'), ('tech', 'Technology'), ('food', 'Food & Beverage'), ('health', 'Health & Wellness'), ('finance', 'Finance & Banking'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('travel', 'Travel & Hospitality'), ('beauty', 'Beauty & Cosmetics'), ('fitness', 'Fitness & Sports'), ('automotive', 'Automotive'), ('retail', 'Retail & E-commerce'), ('other', 'Other')], max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='advertisers/')),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertiser Profile',
                'verbose_name_plural': 'Advertiser Profiles',
            },
        ),
    ]
