# Generated by Django 4.2.6 on 2026-06-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'created_at'], name='application_status_413525_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['campaign', 'status'], name='application_campaig_a88536_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['influencer', 'status'], name='application_influen_ca9d85_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['campaign', 'influencer'], name='application_campaig_b69a3d_idx'),
        ),
    ]
