# Generated by Django 4.2.6 on 2026-05-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du pays')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Code ISO')),
                ('phone_code', models.CharField(max_length=5, verbose_name='Indicatif téléphonique')),
                ('flag_emoji', models.CharField(blank=True, max_length=10, verbose_name='Drapeau emoji')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['name'],
            },
        ),
    ]
