# Generated by Django 4.2.6 on 2026-06-17 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Code ISO (ex: USD, EUR)')),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la monnaie')),
                ('symbol', models.CharField(max_length=5, verbose_name='Symbole (ex: $, €)')),
                ('exchange_rate_to_usd', models.DecimalField(decimal_places=6, default=1.0, max_digits=10, verbose_name='Taux de change vers USD')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Devise',
                'verbose_name_plural': 'Devises',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='core.currency', verbose_name='Devise par défaut'),
        ),
    ]
