# Generated by Django 4.2.6 on 2026-06-20 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_subscription_transaction_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('method_type', models.CharField(choices=[('bank_transfer', 'Virement bancaire'), ('mobile_money', 'Mobile Money (Orange Money, Wave, etc.)'), ('cash', 'Espèces'), ('check', 'Chèque')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de compte')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Nom de la banque')),
                ('instructions', models.TextField(blank=True, verbose_name='Instructions de paiement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Méthode de paiement',
                'verbose_name_plural': 'Méthodes de paiement',
            },
        ),
        migrations.CreateModel(
            name='ManualPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('rejected', 'Rejeté'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Preuve de paiement')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence de transaction')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Raison du rejet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency', verbose_name='Devise')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_payments', to='core.paymentmethod')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_payments', to='core.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement manuel',
                'verbose_name_plural': 'Paiements manuels',
                'ordering': ['-created_at'],
            },
        ),
    ]
