# Generated by Django 4.2.6 on 2026-06-20 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_paymentmethod_manualpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Wariblo', max_length=100, verbose_name='Nom du site')),
                ('site_description', models.TextField(blank=True, verbose_name='Description du site')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone de contact')),
                ('enable_free_plan', models.BooleanField(default=True, verbose_name='Activer le plan gratuit')),
                ('enable_pro_plan', models.BooleanField(default=True, verbose_name='Activer le plan Pro')),
                ('enable_enterprise_plan', models.BooleanField(default=True, verbose_name='Activer le plan Enterprise')),
                ('enable_manual_payments', models.BooleanField(default=True, verbose_name='Activer les paiements manuels')),
                ('payment_instructions', models.TextField(blank=True, verbose_name='Instructions de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.currency', verbose_name='Devise par défaut')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configurations du site',
            },
        ),
    ]
