# Generated by Django 4.2.6 on 2026-06-17 22:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vues totales')),
                ('unique_views', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vues uniques')),
                ('total_clicks', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Clics totaux')),
                ('total_shares', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Partages totaux')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taux de conversion (%)')),
                ('roi', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ROI')),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name="Taux d'engagement (%)")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='campaigns.campaign', verbose_name='Campagne')),
            ],
            options={
                'verbose_name': 'Analytics de campagne',
                'verbose_name_plural': 'Analytics des campagnes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('view', 'Vue'), ('click', 'Clic'), ('apply', 'Candidature'), ('share', 'Partage'), ('message', 'Message'), ('review', 'Avis')], max_length=20, verbose_name="Type d'activité")),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'activité")),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='campaigns.campaign', verbose_name='Campagne')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Activité utilisateur',
                'verbose_name_plural': 'Activités des utilisateurs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_type'], name='analytics_u_user_id_266824_idx'), models.Index(fields=['campaign', 'activity_type'], name='analytics_u_campaig_070de2_idx'), models.Index(fields=['created_at'], name='analytics_u_created_775113_idx')],
            },
        ),
    ]
