# Generated by Django 4.2.6 on 2026-05-14 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('niche', models.CharField(choices=[('fashion', 'Fashion'), ('tech', 'Technology'), ('lifestyle', 'Lifestyle'), ('fitness', 'Fitness & Health'), ('food', 'Food & Cooking'), ('travel', 'Travel'), ('beauty', 'Beauty'), ('gaming', 'Gaming'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('business', 'Business'), ('other', 'Other')], max_length=50)),
                ('instagram_followers', models.PositiveIntegerField(default=0)),
                ('tiktok_followers', models.PositiveIntegerField(default=0)),
                ('youtube_subscribers', models.PositiveIntegerField(default=0)),
                ('twitter_followers', models.PositiveIntegerField(default=0)),
                ('rate_per_post', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='influencers/')),
                ('location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Influencer Profile',
                'verbose_name_plural': 'Influencer Profiles',
            },
        ),
    ]
