# Generated by Django 4.2.6 on 2026-06-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_country_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Vérifié'),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_score',
            field=models.IntegerField(default=50, verbose_name='Score de confiance'),
        ),
    ]
