# Generated by Django 4.2.6 on 2026-06-20 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0003_conversation_messaging_c_updated_7cd0af_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('contact_info', 'Échange de coordonnées'), ('spam', 'Spam'), ('harassment', 'Harcèlement'), ('inappropriate', 'Contenu inapproprié'), ('other', 'Autre')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewed', 'En cours de révision'), ('resolved', 'Résolu'), ('dismissed', 'Rejeté')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='messaging.message')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signalement de message',
                'verbose_name_plural': 'Signalements de messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='messaging_m_status_34e974_idx'), models.Index(fields=['reporter', 'created_at'], name='messaging_m_reporte_556e7f_idx')],
            },
        ),
    ]
