# Generated by Django 4.2.6 on 2026-06-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'created_at'], name='campaigns_c_status_6076a2_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['advertiser', 'status'], name='campaigns_c_adverti_e0256c_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['niche', 'platform'], name='campaigns_c_niche_5c573f_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['deadline'], name='campaigns_c_deadlin_5d0a38_idx'),
        ),
    ]
